### ISSUE TITLE
Provide access to the fetched metadata

### ISSUE THREAD

**Issue by iliana** [awslabs/tough#15]
Add `root`, `snapshot`, and `timestamp` methods to `Repository` to return references to the underlying signed metadata, and change `targets` to do the same, to permit consumers to make small changes to the metadata and re-sign it (such as adding a single target).

**Comment by zmrow** [comment]
I'm just about ready to open a PR for this fix, and have a few questions:

1. Since this is an API breaking change for `tough` (the library), shall we bump it's version to `0.2.0`?
2. I've also had to make a few (tiny) changes to `tuftool` to work with the `tough` library changes. Since they're not API breaking changes, does it seem reasonable to bump `tuftool`'s version to `0.1.1`?
3. Shall i create separate issue and corresponding PR for the `tuftool` changes?

**Comment by iliana** [comment]
> 1. Since this is an API breaking change for `tough` (the library), shall we bump it's version to `0.2.0`?

Yes.

> 2. I've also had to make a few (tiny) changes to `tuftool` to work with the `tough` library changes. Since they're not API breaking changes, does it seem reasonable to bump `tuftool`'s version to `0.1.1`?

No, since I'll bump later. I personally only bump when making changes or doing a release PR.

> 3. Shall i create separate issue and corresponding PR for the `tuftool` changes?

No, CI will fail if tuftool can't compile.
