### ISSUE TITLE
tuftool: support windows

### ISSUE THREAD

**Issue by webern** [awslabs/tough#347]
There are issue with respect to filepaths and failing tests on Windows.

**Comment by Cytro54** [comment]
So, the problem is that, under windows, tests call the `tuftool` binary with raw windows paths (e.g: `c:\foo\bar`), and not URL paths, IMO , there are two solutions to the problem.

- Make tests call tuftool with `file://` like paths.
- Support raw file paths under *nix and Windows.

They all have advantages and problems : 

- If we support raw file paths, it messes up a little of the code, because the cli supports also "aws-ssm://" paths, and it wouldn't be all URLs anymore ; but it will be easier for users to pass a simple path rather than a "file://" address.
- If we simply fix tests, the code would stay uniform, but it would be unusual for users to pass urls to cli instead of file paths.
