### ISSUE TITLE
bump untrusted from 0.7.1 to 0.9+

### ISSUE THREAD

**Issue by webern** [awslabs/tough#395]
Requires some code changes, fails build e.g. #394

**Comment by lrazovic** [comment]
The build fails because the latest public version of `ring` is the `0.16.20`, released 7 months ago, bundled with `untrusted = "0.7.1"`. `untrusted = 0.9` was [added](https://github.com/briansmith/ring/commit/188cc043f7ed17b3fff14f75ea5ac64d2e02d058#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) only on July 14th 2021. So we have to wait for the next version of `ring `to be able to fix this issue.

**Comment by webern** [comment]
Double-checked again. The update to the latest version of untrusted

https://github.com/briansmith/ring/blob/c14c355f51c537c99ff43935c88c22c2e04980a3/Cargo.toml#L165

Was done in this commit in July

https://github.com/briansmith/ring/commit/188cc043f7ed17b3fff14f75ea5ac64d2e02d058

But the latest production release of ring is 0.16.20 from about a year ago

https://crates.io/crates/ring/0.16.20

0.17 is in alpha

https://crates.io/crates/ring/0.17.0-alpha.11

So we will have to wait for ring v0.17 to make dependabot happy about this one.
