### ISSUE TITLE
Move functionality out of tuftool into a library

### ISSUE THREAD

**Issue by zmrow** [awslabs/tough#43]
When it comes to interacting and updating TUF repos, quite a bit of useful functionality is still contained in `tuftool` and isn't usable by outside code. This functionality should be put in a library.

Right off the bat I can see a few functions that should be split out:
* `tuftool/src/create.rs : write_metadata()` : This function takes a role, computes its SHA/length, signs it, and writes it to the TUF output directory
* `tuftool/src/create.rs : process_target()` : Given a `&Path`, this function computes its SHA/length, builds a `Target` object, and writes the file to the appropriate TUF output directory.
*  `tuftool/src/source.rs : KeySource.read()` : Fetching / parsing signing keys is necessary to sign a repo.
* `tuftool/src/key.rs: keys_for_root()` : Given a signing key, get the appropriate root keys.
* `tuftool/src/key.rs : sign_metadata_inner()` : This function does some crucial parsing `root.json` to get the proper keys to use to actually sign.

**Comment by webern** [comment]
@iliana, does this need to wait until you are done with #80, or do you think it is something I could work on now?

**Comment by iliana** [comment]
@webern this can happen whenever, so now works :)

**Comment by zmrow** [comment]
I think the most logical place to start is to extract some of the basic functionality out of tuftool.

This is what I came up with to start. I think most of this can live in `tough`.
* **Create new TUF repo** (`tough/create.rs`)
  * Add a `new()` method to `tough::Repository` that takes in some kind of `CreateArgs` struct and returns a `Repository`.
  * Much of the rest can be lifted almost verbatim from `tuftool`.
    * The `create::CreateArgs` struct becomes a regular struct with sane `Default`s that gets passed to the `new()` call above.
    * The logic currently in `create::CreateProcess.run()` can be adapted for the `Repository::new()` method.

* **Update an existing TUF repo with new targets**
  * Add an `update(&self) -> tough::Repository` method to `tough::Repository`. It will take in an `UpdateArgs` struct and return a brand new `Repository`. (It could optionally write this new Repository's files at a supplied location?)
    * The `UpdateArgs` struct would contain a list of new targets, metadata versions, and expiration dates. Under the hood it would add the new targets, update and sign the metadata.

* **Refresh an existing TUF repo's timestamps**
  * Add a `refresh(&mut self)` method to `tough::Repository` that takes in a `RefreshArgs` struct. (Can be lifted almost verbatim from `tuftool`)
    * This method could work for local (on the filesystem) repos, but we could also think about doing all of this in memory for remote repos. **Is that a bad idea?**

* **Related work**
  * Move the `tuftool::RootDigest` struct into `tough`. **Does this belong in `tough/src/schema`?**
  * `tuftool::metadata::write_metadata()` will most likely get dragged along as a convenience function.
  *  Edit: Define `KeySource` as a trait in `tough` ~~`tuftool::source::KeySource` is sprinkled around the `tuftool` code and I'm not sure yet how I'm going to get around this. I don't think this enum belongs in `tough`.~~

**Comment by webern** [comment]
This all sounds reasonable to me. `RootDigest` maybe isn't the greatest abstraction, but I found that we often need the hash and size of the root.json file along with `Root`. Maybe hash() and size() could just be added to `Root`.

`KeySource` is the biggest problem because it allows us to use `Rusoto` to pull keys from AWS. This functionality probably does not belong in `tough`, yet you definitely want that code to be re-usable. This might be the strongest argument for an intermediate library.

Or, alternatively, maybe the `KeySource` abstraction could be more pluggable (a trait, for example) and the AWS SSM implementation could be a feature (it already is in tuftool I think).

**Comment by zmrow** [comment]
Re: `RootDigest`: I think it's a useful abstraction. @webern Could you elaborate on what you think isn't great about it?

I like the idea of `KeySource` as a trait that we define in `tough`. It keeps `tough` more generic but still allows us to use SSM and files. It also allows us to use this with other providers of the same type of functionality in Azure/GCE, etc.

**Comment by webern** [comment]
I just meant that `RootDigest` does little more than group a couple of pieces of data. But I guess that's what structs are for.

**Comment by zmrow** [comment]
True. The `load_keys` function is pretty dang useful though and one we'll make use of in quite a few places.

**Comment by iliana** [comment]
In terms of the `new()`/`update()`/`refresh()` methods, I think there's a difference between the struct used to read from a repository (which could be available via HTTP, a filesystem, S3, or something we've not thought about yet) and the struct used to modify a repository.

Just having new/update/refresh means you always have to go from one repository to a new one, when you could otherwise be modifying the repository in place. And programs that want to modify existing repositories are not the same as programs that want to use the repository.

So this feels like we want a separate `RepositoryBuilder` struct. It doesn't have any of the validation code because it doesn't need it. It can add/modify targets with some helper functions to hash existing objects on disk. `new()` and `update()` are your higher-level convenience functions. When you're done with it, you call `fn sign(self) -> Result<Repository>` maybe, but really what you want to know is the final path of the metadata and targets directories on your filesystem.

(This naming is very similar to the "builder" initialization model however so a better name might be more appropriate to not confuse developers. `Editor`?)

**Comment by zmrow** [comment]
I'm on board with that strategy. We'll go with `RepositoryEditor`. 😄
